version: "3.8"

services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate --run-syncdb && python manage.py runserver 0.0.0.0:8000"
    image: chatapp:v1
    ports:
      - "8000:8000"
